# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'
services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: ${SENTRY_POSTGRES_HOST}
      SENTRY_EMAIL_HOST: ${SENTRY_EMAIL_HOST}
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_DB_NAME: sentry_prod
      SENTRY_DB_USER: sentry_user
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_PASSWORD:  ${EMAIL_HOST_PASSWORD}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_USE_TLS: 'True'
    volumes:
      - ./data/sentry:/var/lib/sentry/files

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  web:
    extends: base
    links:
      - redis
      - memcached
    ports:
      - '80:9000'

  cron:
    extends: base
    command: run cron
    links:
      - redis
      - memcached

  worker:
    extends: base
    command: run worker
    links:
      - redis
      - memcached

