# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'
services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
      SENTRY_SECRET_KEY: '1u2aq79qp6kni07tf&mk*wo!nmil9%^85m_4cmz5ziha=8&)4t'
      SENTRY_DB_NAME: sentry_prod
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: '6oWhjZyHBi4'
      EMAIL_HOST: smtp.gmail.com
      EMAIL_HOST_PASSWORD: 'ezqsfylfzksfgyfq'
      EMAIL_HOST_USER: 'alerts@yougotagift.com'
      EMAIL_USE_TLS: 'True'
    volumes:
      - ./data/sentry:/var/lib/sentry/files

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=6oWhjZyHBi4"
      - "POSTGRES_DB=sentry_prod"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    extends: base
    environment:
      - "SENTRY_SECRET_KEY=1u2aq79qp6kni07tf&mk*wo!nmil9%^85m_4cmz5ziha=8&)4t"
      - "SENTRY_DB_NAME=sentry_prod"
      - "SENTRY_DB_USER=postgres"
      - "SENTRY_DB_PASSWORD=6oWhjZyHBi4"
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_HOST_PASSWORD=ezqsfylfzksfgyfq"
      - "EMAIL_HOST_USER=alerts@yougotagift.com"
      - "EMAIL_USE_TLS=True"
    links:
      - redis
      - postgres
      - memcached
    ports:
      - '80:9000'

  cron:
    extends: base
    command: run cron
    environment:
      - "SENTRY_SECRET_KEY=1u2aq79qp6kni07tf&mk*wo!nmil9%^85m_4cmz5ziha=8&)4t"
      - "SENTRY_DB_NAME=sentry_prod"
      - "SENTRY_DB_USER=postgres"
      - "SENTRY_DB_PASSWORD=6oWhjZyHBi4"
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_HOST_PASSWORD=ezqsfylfzksfgyfq"
      - "EMAIL_HOST_USER=alerts@yougotagift.com"
      - "EMAIL_USE_TLS=True"
    links:
      - redis
      - postgres
      - memcached

  worker:
    extends: base
    command: run worker
    environment:
      - "SENTRY_SECRET_KEY=1u2aq79qp6kni07tf&mk*wo!nmil9%^85m_4cmz5ziha=8&)4t"
      - "SENTRY_DB_NAME=sentry_prod"
      - "SENTRY_DB_USER=postgres"
      - "SENTRY_DB_PASSWORD=6oWhjZyHBi4"
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_HOST_PASSWORD=ezqsfylfzksfgyfq"
      - "EMAIL_HOST_USER=alerts@yougotagift.com"
      - "EMAIL_USE_TLS=True"
    links:
      - redis
      - postgres
      - memcached

